name: Run Basic Tests

on: 
  pull_request:
    branches: [master]

jobs:
  cypress-run:
    runs-on: windows-latest

    steps:
      - name: Checkout/Clone do projeto
        uses: actions/checkout@v4

      - name: Install root dependencies
        run: npm install --package-lock-only
        
      # - name: Install root dependencies
      #   run: 
      #     npm install --package-lock-only
      #     npm ci
        
      # - name: Start server in the background
      #   run: npm start &

      - name: Install Cypress and run tests
        uses: cypress-io/github-action@v6
        with:
          record: true
          # working-directory: e2e
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}